### ISSUE TITLE
Not starting with python 3.10.8 macOS/Apple Silicone

### ISSUE THREAD

**Issue by microfx** [chaiNNer-org/chaiNNer-nightly#2]
Hey! 
Trying to use chaiNNer with my python 3.10.8 to use it with latest PyTorch for Apple Silicone and it won't start 

```
"The Python backend encountered an unexpected error. ChaiNNer will now exit. Error: Error: spawn "/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10" ENOENT"
```
```
/Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10 --version          
Python 3.10.8
```

Any idea what I could do?

**Comment by joeyballentine** [comment]
Someone else (maybe it was use, i only just realized this ticket was open) reported this as well, and I'm not really sure why it would be doing this. My only guess is it's some macos or Unix specific thing related to paths since selecting a python path works fine on windows. I would need to further debug it on a Mac system

**Comment by joeyballentine** [comment]
The best thing to try would be to clear the custom python path and just make sure your python3 alias in your terminal points to the right one so chainner is able to automatically find it through that rather than the full path

**Comment by microfx** [comment]
we talked on discord - I tried EVERYTHING even with custom venv etc. pp. - really everything. If you want I can give you remote access to my mac. Hit me up on discord (vortex)

**Comment by joeyballentine** [comment]
Ah ok, i didn't know if this was you. We can talk about it more on discord
